###
# Requisições para a API Todo
###

# Base URL da API
@base_url = http://localhost:3000

# Obter todas as tarefas
GET {{base_url}}/todo

# Obter uma tarefa por ID
GET {{base_url}}/todo/1

# Criar uma nova tarefa
POST {{base_url}}/todo
Content-Type: application/json

{
    "title": "Minha nova tarefa",
    "description": "Uma descrição opcional da tarefa"
}

# Atualizar uma tarefa existente
PUT {{base_url}}/todo/1
Content-Type: application/json

{
    "title": "Tarefa atualizada",
    "description": "Descrição atualizada"
}

# Excluir uma tarefa por ID
DELETE {{base_url}}/todo/1
